[programs.localnet]
omnichain_payroll = "omnichain_payroll1111111111111111111111111111111"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test-bpf"